GET http://localhost:3002/health

###

GET http://localhost:3002/api/v1/users/test
Authorization: 
###

POST http://localhost:3002/api/v1/users/test6
Content-Type: application/json

{
  "password": "test6"
}

###

POST http://localhost:3002/api/v1/keys/test5
Content-Type: application/json

###

GET http://localhost:3002/api/v1/keys/key/33e562ca7ff9fde8fd1fe8ab08cd16cbc9de9b5c7caa29cbeb11f5655c1e5469
user-id: test

###

GET http://localhost:3002/api/v1/keys/user/testrrr
user-id: test


###

POST http://localhost:3002/api/v1/login
Content-Type: application/json

{
  "userId": "test6",
  "password": "test6"
}

###

GET http://localhost:3002/api/v1/login/auth
Authorization: 

###

POST http://localhost:3002/api/v1/todo
Content-Type: application/json
user-id: test6

{
  "name": "Test todo2",
  "description": "Do some great stuff",
  "priority": 2,
  "dueDate": 1617106687
}


###

GET http://localhost:3002/api/v1/todo/2

###

GET http://localhost:3002/api/v1/todo/user/test6
