GET http://localhost:3000/users/test

###

POST http://localhost:3000/users/test6
Content-Type: application/json

{
  "password": "test6"
}

###

POST http://localhost:3000/keys/test5
Content-Type: application/json

###

GET http://localhost:3000/keys/key/33e562ca7ff9fde8fd1fe8ab08cd16cbc9de9b5c7caa29cbeb11f5655c1e5469
user-id: test

###

GET http://localhost:3000/keys/user/testrrr
user-id: test


###

POST http://localhost:3000/login
Content-Type: application/json

{
  "userId": "test6",
  "password": "test6"
}

###

GET http://localhost:3000/login/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdTE5ODciLCJ1c2VySWQiOiJ0ZXN0NiIsImlhdCI6MTYxNTYwMDAzMywiZXhwIjoxNjE1NjAwMDQ4fQ.-iVfaJMn7hLmfYt8pqsllZnbr2U-VvXHQ0lGSjlPFDg