postgresql:
  image: postgres:12.7
  container_name: postgresql
  env_file:
    - .env
  ports:
    - 5433:5432
  volumes:
    - ./postgres/init:/docker-entrypoint-initdb.d
    - postgresql_data:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASS}
    POSTGRES_DB: ${DB_NAME}
  hostname: postgres
  restart: always
  user: root
